### ISSUE TITLE
报错无法解决望解答

### ISSUE THREAD

**Issue by zhongwei1122** [cfzd/Ultra-Fast-Lane-Detection-v2#69]
执行sh.build.sh一直报错TypeError: expected string or bytes-like object不知道怎么解决，运行demo.py时torch not compiled with CUDA enabled，更换pytorch版本还是没用

**Comment by cfzd** [comment]
@zhongwei1122 
可以贴一下报错截图吗

**Comment by 1605707467qq** [comment]
您好这是我的报错截图
![image](https://user-images.githubusercontent.com/69078348/206646090-8988ba56-c98e-4133-bd90-db9c9ba4bc35.png)

No CUDA runtime is found, using CUDA_HOME=':/usr/local/cuda-11.1:/usr/local/cuda-11.1'
running install
/home/mengxc/local/Anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/mengxc/local/Anaconda3/envs/lane-det/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing my_interp.egg-info/PKG-INFO
writing dependency_links to my_interp.egg-info/dependency_links.txt
writing top-level names to my_interp.egg-info/top_level.txt
/home/mengxc/local/Anaconda3/envs/lane-det/lib/python3.7/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'my_interp.egg-info/SOURCES.txt'
writing manifest file 'my_interp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.1:/usr/local/cuda-11.1/bin/nvcc': ':/usr/local/cuda-11.1:/usr/local/cuda-11.1/bin/nvcc'

有个愚昧的问题，我装的是md中的，10.2，我环境是11.1😢

**Comment by zhangwulong** [comment]
我遇到的也是这个问题，安装my_interp失败，如果在cuda11.x上安装，会显示安装的是my_interp=0.0.0，训练时会报my_interp have no module named ‘run’的报错。
感觉安装需要特定的环境，但是还没成功

**Comment by cfzd** [comment]
@1605707467qq 
`nvcc`是cuda的编译器，你可以理解为c语言的gcc。报错提示你没有这个肯定是编译不了的，你确定你的cuda安装好了吗，尤其是在`/usr/local/cuda-11.1`这个路径。

@zhangwulong 
0.0.0是没有问题的，它只是一个版本号，默认就是0.0.0。只要：
- 你的pytorch使用的cuda版本和你编译`my_interp`用的cuda是同一个版本
那么在任意cuda版本上都可以工作，`my_interp`只是一个非常简单的插件

**Comment by zhangwulong** [comment]
您发的邮件已收到，谢谢——武龙

**Comment by awethaileslassie** [comment]
Installing cuda/gpu compatible torch solved my problem.

please check if your installed torch support gpu:
```
import torch
torch.cuda.is_available()
```

**Comment by zhangwulong** [comment]
您发的邮件已收到，谢谢——武龙
